name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # 北京时间早晨 08:00 == UTC 时间 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          # 建议使用默认的 GITHUB_TOKEN，除非有特殊权限需求
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'generated 3d contribution graph'